In [17]:
import numpy as np
import pandas as pd

# import ordinal encoder - this is used to encode ordinal input features
from sklearn.preprocessing import OrdinalEncoder
# import label encoder - this is used to encode ordinal target features
from sklearn.preprocessing import LabelEncoder
# import one hot encoder - used to encode nominal input features (this can also be used for dummy encoding)
from sklearn.preprocessing import OneHotEncoder


## Ordinal Encoding Examples

In [18]:
# create a list of lists to represent the input data
data = [['red', 2], ['green', 3], ['blue', 1]]

# create an instance of the ordinal encoder
encoder = OrdinalEncoder()

# fit the encoder to the data
encoder.fit(data)

# transform the data
encoded_data = encoder.transform(data)

# print the encoded data
print(encoded_data)


[[2. 1.]
 [1. 2.]
 [0. 0.]]


In [19]:
# create a list of lists to represent the input data
data = [['warm', 2], ['hot', 3], ['cold', 1]]

# create an instance of the ordinal encoder
encoder = OrdinalEncoder()

# fit the encoder to the data
encoder.fit(data)

# transform the data
encoded_data = encoder.transform(data)

# print the encoded data
print(encoded_data)


[[2. 1.]
 [1. 2.]
 [0. 0.]]


In [20]:
# create a list of lists to represent the input data
data = [['warm', 2], ['hot', 3], ['cold', 1]]

# create an instance of the ordinal encoder
encoder = OrdinalEncoder(categories=[['cold', 'warm', 'hot'], [1, 2, 3]])

# fit the encoder to the data
encoder.fit(data)

# transform the data
encoded_data = encoder.transform(data)

# print the encoded data
print(encoded_data)


[[1. 1.]
 [2. 2.]
 [0. 0.]]


## One Hot Encoding Examples

In [45]:

# create a list of lists to represent the input data
data = [['dog', 2], ['cat', 3], ['horse', 1]]
df = pd.DataFrame(data, columns=['animal', 'age'])

df = pd.get_dummies(df, columns=['animal'], prefix='a', prefix_sep='-')

df

age  a-cat  a-dog  a-horse
0    2  False   True    False
1    3   True  False    False
2    1  False  False     True

In [51]:

# create a list of lists to represent the input data
data = [['dog', 2], ['cat', 3], ['horse', 1]]
df = pd.DataFrame(data, columns=['animal', 'age'])

df = pd.get_dummies(df, columns=['animal'], prefix='a', prefix_sep='-', drop_first=True)

df['a-dog'] = df['a-dog'].astype('int')
df

age  a-dog  a-horse
0    2      1    False
1    3      0    False
2    1      0     True

# Label Encoding

In [63]:
# create a list of lists to represent the input data

data = [[1,2,'dog'], [2,2,'cat'], [3,1,'horse']]
df = pd.DataFrame(data, columns=['num1','num2','animal'])


# create an instance of the label encoder
encoder = LabelEncoder()

# fit the encoder to the data
df['animal'] = encoder.fit_transform(df['animal'])

# print the encoded data
print(df)

   num1  num2  animal
0     1     2       1
1     2     2       0
2     3     1       2
